name: LiteWaffle
main: com.discord.sapokr.litewaffle.LiteWaffle
version: 1.1
description: LiteWaffle from TDMManagerV2
author: SapoKR
website: https://github.com/HappyPlayground/LiteWaffle
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.0
  - net.dv8tion:JDA:5.0.0-alpha.4
  - club.minnced:discord-webhooks:0.7.5
commands:
  litewaffle:
    description: litewaffle configuation
    permissions: litewaffle.configuation
